# Generated by Django 6.0.4 on 2026-05-21 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategoriya nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='category_audio/', verbose_name='Kategoriya audio fayli')),
                ('max_audio_plays', models.IntegerField(default=1, verbose_name='Audio necha marta eshitilishi mumkin (0=cheksiz)')),
                ('audio_instruction', models.TextField(blank=True, null=True, verbose_name="Audio uchun qo'shimcha ko'rsatma")),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Guruh nomi')),
                ('teacher', models.CharField(max_length=200, verbose_name="O'qituvchi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Video URL')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='rules_videos/', verbose_name='Video fayl')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='rules_images/', verbose_name='Rasm 1')),
                ('image1_title', models.CharField(blank=True, default='Imtihon tartibi', max_length=200)),
                ('image1_description', models.TextField(blank=True, default="Imtihon vaqtida nimalarga e'tibor berish kerak")),
                ('image2', models.ImageField(blank=True, null=True, upload_to='rules_images/', verbose_name='Rasm 2')),
                ('image2_title', models.CharField(blank=True, default='Baholash mezonlari', max_length=200)),
                ('image2_description', models.TextField(blank=True, default='Qanday qilib yuqori ball olish mumkin')),
                ('rules_text', models.TextField(default="1. Telefon va qurilmalardan foydalanish QAT'IY MAN ETILADI\n2. Belgilangan vaqtda topshirish shart\n3. Ko'chirish qat'iyan man etiladi\n4. Texnik muammoda o'qituvchiga murojaat qiling\n5. Natijalar tekshiruvdan keyin e'lon qilinadi")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Qonun va qoidalar',
                'verbose_name_plural': 'Qonun va qoidalar',
            },
        ),
        migrations.CreateModel(
            name='AdminPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plain_password', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_password', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin paroli',
                'verbose_name_plural': 'Admin parollari',
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='groups.group')),
            ],
            options={
                'verbose_name': 'Imtihon sessiyasi',
                'verbose_name_plural': 'Imtihon sessiyalari',
            },
        ),
        migrations.CreateModel(
            name='ExamControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_control', to='groups.group')),
            ],
            options={
                'verbose_name': 'Imtihon boshqaruvi',
                'verbose_name_plural': 'Imtihon boshqaruvlari',
            },
        ),
        migrations.CreateModel(
            name='GroupExamConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_category_configs', models.BooleanField(default=True, verbose_name='Kategoriya sozlamalaridan foydalanish')),
                ('questions_per_student', models.IntegerField(default=10, verbose_name='Har talaba uchun savollar soni')),
                ('total_questions', models.IntegerField(default=10, verbose_name='Jami savollar soni')),
                ('random_order', models.BooleanField(default=True, verbose_name='Random tartib')),
                ('show_correct_answer', models.BooleanField(default=False, verbose_name="To'g'ri javobni ko'rsatish")),
                ('time_limit', models.IntegerField(default=0, verbose_name='Vaqt limiti (daqiqa)')),
                ('max_attempts', models.IntegerField(default=1, verbose_name='Maksimal urinishlar')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='exam_audio/', verbose_name='Imtihon audio fayli')),
                ('max_audio_plays', models.IntegerField(default=1, verbose_name='Audio necha marta eshitilishi mumkin')),
                ('audio_instruction', models.TextField(blank=True, null=True, verbose_name="Audio ko'rsatmasi")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_config', to='groups.group')),
            ],
            options={
                'verbose_name': 'Imtihon sozlamasi',
                'verbose_name_plural': 'Imtihon sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
            options={
                'verbose_name': 'Quiz sessiyasi',
                'verbose_name_plural': 'Quiz sessiyalari',
            },
        ),
        migrations.CreateModel(
            name='ReadingText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Matn sarlavhasi')),
                ('content', models.TextField(verbose_name='Matn mazmuni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_texts', to='groups.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Matn',
                'verbose_name_plural': 'Matnlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Savol matni')),
                ('correct_answer', models.CharField(max_length=500, verbose_name="To'g'ri javob")),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('reading_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_questions', to='groups.readingtext', verbose_name='Matn')),
            ],
            options={
                'verbose_name': 'Matn savoli',
                'verbose_name_plural': 'Matn savollari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('fill_blank', "Bo'sh joy to'ldirish (Word Bank)"), ('fill_blank_no_word', "Bo'sh joy to'ldirish (Variantlarsiz)"), ('sentence_arrangement', "So'zlarni tartibga solish"), ('multiple_choice', 'Test varianti'), ('true_false', "To'g'ri/Noto'g'ri"), ('reading_comprehension', 'Matn asosida savol'), ('underline_correct', "To'g'ri so'zni tanlash"), ('matching', 'Moslashtirish'), ('cloze_multiple_blanks', "Matn ichidagi bo'sh joylar"), ('complete_the_words', "So'zlarni to'ldirish (birinchi harf berilgan)")], default='fill_blank', max_length=30, verbose_name='Savol turi')),
                ('question_text', models.TextField(blank=True, null=True, verbose_name='Savol matni')),
                ('correct_answer', models.TextField(blank=True, max_length=2000, null=True, verbose_name="To'g'ri javob")),
                ('scrambled_words', models.TextField(blank=True, null=True, verbose_name="Chalkashtirilgan so'zlar / Variantlar / Matching data")),
                ('correct_sentence', models.TextField(blank=True, null=True, verbose_name="To'g'ri gap")),
                ('blank_options', models.JSONField(blank=True, default=dict, null=True, verbose_name="Bo'sh joy variantlari")),
                ('blank_positions', models.JSONField(blank=True, default=dict, null=True, verbose_name="Bo'sh joy pozitsiyalari")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='groups.category', verbose_name='Kategoriya')),
                ('reading_text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='groups.readingtext', verbose_name='Matn')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['category__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='groups.group', verbose_name='Guruh')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Ball')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Jami savollar')),
                ('answers', models.JSONField(default=dict, verbose_name='Javoblar')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('attempt_number', models.IntegerField(default=1, verbose_name='Urinish raqami')),
                ('quiz_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='groups.quizsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='groups.student')),
            ],
            options={
                'verbose_name': 'Quiz natijasi',
                'verbose_name_plural': 'Quiz natijalari',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('answers', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='groups.examsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='groups.student')),
            ],
            options={
                'verbose_name': 'Imtihon natijasi',
                'verbose_name_plural': 'Imtihon natijalari',
            },
        ),
        migrations.CreateModel(
            name='UserExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_questions', models.JSONField(default=list, verbose_name='Tanlangan savollar')),
                ('user_answers', models.JSONField(blank=True, default=dict, verbose_name='Foydalanuvchi javoblari')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('attempt_number', models.IntegerField(default=1, verbose_name='Urinish raqami')),
                ('exam_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='groups.quizsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='groups.student')),
            ],
            options={
                'verbose_name': 'Imtihon urinishi',
                'verbose_name_plural': 'Imtihon urinishlari',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryGroupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_count', models.IntegerField(default=5, verbose_name='Savollar soni')),
                ('random_order', models.BooleanField(default=True, verbose_name='Random tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_configs', to='groups.category')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_configs', to='groups.group')),
            ],
            options={
                'verbose_name': 'Kategoriya guruh sozlamasi',
                'verbose_name_plural': 'Kategoriya guruh sozlamalari',
                'unique_together': {('category', 'group')},
            },
        ),
        migrations.CreateModel(
            name='GroupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_categories', to='groups.category')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_categories', to='groups.group')),
            ],
            options={
                'verbose_name': 'Guruh kategoriyasi',
                'verbose_name_plural': 'Guruh kategoriyalari',
                'unique_together': {('group', 'category')},
            },
        ),
        migrations.CreateModel(
            name='StudentAudioPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_count', models.IntegerField(default=0)),
                ('max_plays', models.IntegerField(default=1)),
                ('last_played_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.category')),
                ('exam_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.quizsession')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_plays', to='groups.student')),
            ],
            options={
                'verbose_name': 'Student audio ijrosi',
                'verbose_name_plural': 'Student audio ijrolari',
                'unique_together': {('student', 'group', 'category', 'exam_session')},
            },
        ),
        migrations.CreateModel(
            name='StudentQuestionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.category')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.quizquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_history', to='groups.student')),
            ],
            options={
                'ordering': ['seen_at'],
                'unique_together': {('student', 'category', 'question')},
            },
        ),
    ]
