# Generated by Django 6.0.4 on 2026-05-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_examcontrol_elapsed_time_examcontrol_is_paused_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examcontrol',
            name='total_paused_time',
        ),
    ]
