# Generated by Django 6.0.4 on 2026-05-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_examcontrol_total_paused_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='score',
            field=models.FloatField(default=0, verbose_name='Ball (0-100)'),
        ),
    ]
