# Generated by Django 6.0.4 on 2026-05-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_quizresult_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('fill_blank', 'Fill Blank'), ('fill_blank_no_word', 'Fill Blank No Word'), ('multiple_choice', 'Multiple Choice'), ('underline_correct', 'Underline Correct'), ('true_false', 'True / False'), ('matching', 'Matching'), ('cloze_multiple_blanks', 'Cloze Multiple Blanks'), ('complete_the_words', 'Complete The Words'), ('reading_comprehension', 'Reading Comprehension')], default='fill_blank', max_length=30, verbose_name='Savol turi'),
        ),
    ]
