# Generated by Django 6.0.4 on 2026-05-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_quizquestion_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='blank_options',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='blank_positions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='scrambled_words',
            field=models.TextField(blank=True, null=True, verbose_name="Chalkashtirilgan so'zlar"),
        ),
    ]
