# Generated by Django 6.0.4 on 2026-05-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_alter_quizquestion_blank_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='points',
            field=models.IntegerField(default=1, verbose_name='Ball'),
        ),
    ]
