# Generated by Django 6.0.4 on 2026-05-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_quizquestion_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('fill_blank', "Bo'sh joy to'ldirish (Word Bank)"), ('fill_blank_no_word', "Bo'sh joy to'ldirish (Variantlarsiz)"), ('sentence_arrangement', "So'zlarni tartibga solish"), ('multiple_choice', 'Test varianti'), ('true_false', "To'g'ri/Noto'g'ri"), ('reading_comprehension', 'Matn asosida savol'), ('underline_correct', "To'g'ri so'zni tanlash"), ('matching', 'Moslashtirish'), ('cloze_multiple_blanks', "Matn ichidagi bo'sh joylar"), ('complete_the_words', "So'zlarni to'ldirish (birinchi harf berilgan)"), ('writing', 'Yozma ish (Writing)')], default='fill_blank', max_length=30, verbose_name='Savol turi'),
        ),
    ]
