# Generated by Django 4.2 on 2026-06-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_alter_quizquestion_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupexamconfig',
            name='grading_enabled',
            field=models.BooleanField(default=False, verbose_name='Baholash tizimini yoqish'),
        ),
        migrations.AddField(
            model_name='groupexamconfig',
            name='high_threshold',
            field=models.IntegerField(default=70, verbose_name="O'rta/yuqori chegarasi (%)"),
        ),
        migrations.AddField(
            model_name='groupexamconfig',
            name='label_high',
            field=models.CharField(default='Yuqori', max_length=50, verbose_name='Yuqori uchun yorliq'),
        ),
        migrations.AddField(
            model_name='groupexamconfig',
            name='label_low',
            field=models.CharField(default='Past', max_length=50, verbose_name='Past uchun yorliq'),
        ),
        migrations.AddField(
            model_name='groupexamconfig',
            name='label_medium',
            field=models.CharField(default="O'rta", max_length=50, verbose_name="O'rta uchun yorliq"),
        ),
        migrations.AddField(
            model_name='groupexamconfig',
            name='low_threshold',
            field=models.IntegerField(default=40, verbose_name="Past/o'rta chegarasi (%)"),
        ),
    ]
