# Generated by Django 4.2 on 2026-06-01 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_groupexamconfig_grading_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCameraFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('exam_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera_feeds', to='groups.examsession')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_feeds', to='groups.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_feeds', to='groups.student')),
            ],
            options={
                'verbose_name': 'Kamera tasmasi',
                'verbose_name_plural': 'Kamera tasmalari',
            },
        ),
        migrations.CreateModel(
            name='ExamCameraSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.TextField(verbose_name='Rasm (base64)')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='groups.examcamerafeed')),
            ],
            options={
                'verbose_name': 'Kamera surati',
                'verbose_name_plural': 'Kamera suratlari',
                'ordering': ['-captured_at'],
            },
        ),
    ]
