# Generated by Django 4.2 on 2026-06-01 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_examcamerafeed_examcamerasnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True, verbose_name='Qurilma ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomi')),
                ('user_agent', models.TextField(blank=True, verbose_name="Brauzer ma'lumoti")),
                ('ip_address', models.CharField(blank=True, max_length=45, verbose_name='IP manzil')),
                ('platform', models.CharField(blank=True, max_length=100, verbose_name='Platforma')),
                ('screen_resolution', models.CharField(blank=True, max_length=20, verbose_name="Ekran o'lchami")),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name="Oxirgi ko'rilgan")),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name="Birinchi ko'rilgan")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='groups.group')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='groups.student')),
            ],
            options={
                'verbose_name': 'Qurilma',
                'verbose_name_plural': 'Qurilmalar',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.RemoveField(
            model_name='examcamerasnapshot',
            name='feed',
        ),
        migrations.DeleteModel(
            name='ExamCameraFeed',
        ),
        migrations.DeleteModel(
            name='ExamCameraSnapshot',
        ),
    ]
