# Generated by Django 4.2 on 2026-06-01 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_device_remove_examcamerasnapshot_feed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='group_name_saved',
            field=models.CharField(blank=True, max_length=100, verbose_name='Guruh nomi (saqlangan)'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='student_name_saved',
            field=models.CharField(blank=True, max_length=200, verbose_name='Student nomi (saqlangan)'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='quiz_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='groups.quizsession'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_results', to='groups.student'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group'),
        ),
    ]
