# Generated by Django 4.2 on 2026-06-01 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_quizresult_group_name_saved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='group_name_saved',
            field=models.CharField(blank=True, max_length=100, verbose_name='Guruh nomi (saqlangan)'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='student_name_saved',
            field=models.CharField(blank=True, max_length=200, verbose_name='Student nomi (saqlangan)'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='exam_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='groups.examsession'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_results', to='groups.student'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_sessions', to='groups.group'),
        ),
    ]
