# Generated by Django 4.2 on 2026-06-01 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_examresult_group_name_saved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaudioplay',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group'),
        ),
        migrations.AlterField(
            model_name='studentaudioplay',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_plays', to='groups.student'),
        ),
    ]
