# Generated by Django 4.2 on 2026-06-01 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0016_alter_studentaudioplay_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(related_name='teachers', to='groups.group', verbose_name='Guruhlar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
            },
        ),
        migrations.CreateModel(
            name='TeacherScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name_saved', models.CharField(blank=True, max_length=200, verbose_name='Student nomi (saqlangan)')),
                ('group_name_saved', models.CharField(blank=True, max_length=100, verbose_name='Guruh nomi (saqlangan)')),
                ('score_added', models.IntegerField(default=0, verbose_name="Qo'shilgan ball")),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_score_logs', to='groups.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_logs', to='groups.teacher')),
            ],
            options={
                'verbose_name': "O'qituvchi ball qo'shish",
                'verbose_name_plural': "O'qituvchi ball qo'shishlar",
                'ordering': ['-created_at'],
            },
        ),
    ]
