# Generated by Django 4.2 on 2026-06-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0017_teacher_teacherscorelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='all_groups',
            field=models.BooleanField(default=False, verbose_name='Barcha guruhlarga kirish'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='groups.group', verbose_name='Guruhlar'),
        ),
    ]
