# Generated by Django 4.2 on 2026-06-01 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0018_teacher_all_groups_alter_teacher_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.CreateModel(
            name='AssessmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('speaking', "Og'zaki (Speaking)"), ('written', 'Yozma ish (Written)')], max_length=20, verbose_name='Baholash turi')),
                ('score', models.IntegerField(default=0, verbose_name='Ball')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('student_name_saved', models.CharField(blank=True, max_length=200, verbose_name='Student nomi (saqlangan)')),
                ('group_name_saved', models.CharField(blank=True, max_length=100, verbose_name='Guruh nomi (saqlangan)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_assessments', to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan foydalanuvchi")),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_scores', to='groups.student')),
            ],
            options={
                'verbose_name': 'Baholash',
                'verbose_name_plural': 'Baholashlar',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'group', 'assessment_type')},
            },
        ),
    ]
