# Generated by Django 4.2 on 2026-06-01 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0019_teacher_is_active_assessmentscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='certificate_bg/', verbose_name='Sertifikat fon rasmi')),
                ('threshold_percentage', models.IntegerField(default=50, verbose_name='Sertifikat olish uchun minimal ball (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sertifikat sozlamasi',
                'verbose_name_plural': 'Sertifikat sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200, verbose_name='Student ismi')),
                ('group_name', models.CharField(max_length=100, verbose_name='Guruh nomi')),
                ('score', models.FloatField(verbose_name='Ball')),
                ('certificate_file', models.FileField(upload_to='certificates/', verbose_name='Sertifikat fayli')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('quiz_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='groups.quizresult', verbose_name='Test natijasi')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'ordering': ['-generated_at'],
            },
        ),
    ]
