# Generated by Django 4.2 on 2026-06-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0020_certificatesetting_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupexamconfig',
            name='certificate_enabled',
            field=models.BooleanField(default=False, verbose_name='Sertifikat berish'),
        ),
        migrations.AddField(
            model_name='groupexamconfig',
            name='certificate_level',
            field=models.CharField(blank=True, help_text='Masalan: A1, A2, B1, B2, C1, C2', max_length=100, null=True, verbose_name='Sertifikat darajasi'),
        ),
        migrations.AddField(
            model_name='groupexamconfig',
            name='certificate_teacher',
            field=models.CharField(blank=True, help_text="Bo'sh qoldirilsa, guruh o'qituvchisi ishlatiladi", max_length=200, null=True, verbose_name="Sertifikatdagi o'qituvchi ismi"),
        ),
    ]
