# Generated by Django 4.2 on 2026-06-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0021_groupexamconfig_certificate_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arxivlangan'),
        ),
    ]
