# Generated by Django 4.2 on 2026-06-03 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0022_certificate_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquestionhistory',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_history', to='groups.student'),
        ),
        migrations.AlterField(
            model_name='userexamattempt',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_attempts', to='groups.student'),
        ),
    ]
