# Generated by Django 4.2 on 2026-06-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0023_alter_studentquestionhistory_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arxivlangan'),
        ),
        migrations.AddField(
            model_name='student',
            name='rules_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Qoidalarni qabul qilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='groupexamconfig',
            name='certificate_enabled',
            field=models.BooleanField(default=True, verbose_name='Sertifikat berish'),
        ),
    ]
