# Generated by Django 4.2 on 2026-06-08 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0024_student_is_archived_student_rules_accepted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Papka nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Papka',
                'verbose_name_plural': 'Papkalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_groups', to='groups.folder')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_folders', to='groups.group')),
            ],
            options={
                'verbose_name': 'Guruh papkasi',
                'verbose_name_plural': 'Guruh papkalari',
                'unique_together': {('group', 'folder')},
            },
        ),
        migrations.CreateModel(
            name='FolderGroupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_to_select', models.IntegerField(default=1, verbose_name='Tanlanadigan kategoriyalar soni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_group_configs', to='groups.folder')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_configs', to='groups.group')),
            ],
            options={
                'verbose_name': 'Papka guruh sozlamasi',
                'verbose_name_plural': 'Papka guruh sozlamalari',
                'unique_together': {('folder', 'group')},
            },
        ),
        migrations.CreateModel(
            name='FolderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_folders', to='groups.category')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_categories', to='groups.folder')),
            ],
            options={
                'verbose_name': 'Papka kategoriyasi',
                'verbose_name_plural': 'Papka kategoriyalari',
                'unique_together': {('folder', 'category')},
            },
        ),
    ]
