# Generated by Django 4.2 on 2026-06-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0025_folder_groupfolder_foldergroupconfig_foldercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='foldergroupconfig',
            name='randomize_categories',
            field=models.BooleanField(default=True, verbose_name='Random tanlash'),
        ),
    ]
