# Generated by Django 5.2.15 on 2026-06-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0026_foldergroupconfig_randomize_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupexamconfig',
            name='show_points_to_student',
            field=models.BooleanField(default=False, verbose_name="Talabaga ballni ko'rsatish"),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('fill_blank', "Bo'sh joy to'ldirish (Word Bank)"), ('fill_blank_no_word', "Bo'sh joy to'ldirish (Variantlarsiz)"), ('sentence_arrangement', "So'zlarni tartibga solish"), ('multiple_choice', 'Test varianti'), ('true_false', "To'g'ri/Noto'g'ri"), ('reading_comprehension', 'Matn asosida savol'), ('underline_correct', "To'g'ri so'zni tanlash"), ('matching', 'Moslashtirish'), ('cloze_multiple_blanks', "Matn ichidagi bo'sh joylar"), ('complete_the_words', "So'zlarni to'ldirish (birinchi harf berilgan)"), ('match_fill', "So'zlarni matnga mos qo'yish"), ('writing', 'Yozma ish (Writing)'), ('speaking', "Og'zaki (Speaking)"), ('plain_text', 'Oddiy matn')], default='fill_blank', max_length=30, verbose_name='Savol turi'),
        ),
    ]
