# Generated by Django 5.2.15 on 2026-06-12 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0027_groupexamconfig_show_points_to_student_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerToggleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=20, verbose_name='Savol ID')),
                ('blank_num', models.CharField(blank=True, max_length=10, null=True, verbose_name="Bo'sh joy")),
                ('was_correct', models.BooleanField(verbose_name='Oldingi holat')),
                ('now_correct', models.BooleanField(verbose_name='Hozirgi holat')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgartirilgan vaqt")),
                ('quiz_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toggle_history', to='groups.quizresult')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan")),
            ],
            options={
                'verbose_name': "Javob o'zgartirish tarixi",
                'verbose_name_plural': "Javob o'zgartirish tarixlari",
                'ordering': ['-changed_at'],
            },
        ),
    ]
