# Generated by Django 5.2.15 on 2026-06-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0028_answertogglehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='points',
            field=models.FloatField(default=1.0, verbose_name='Ball'),
        ),
    ]
