# Generated by Django 5.2.15 on 2026-06-15 04:48

import django.db.models.deletion
from django.db import migrations, models


def migrate_category_audio_forward(apps, schema_editor):
    Category = apps.get_model('groups', 'Category')
    CategoryAudio = apps.get_model('groups', 'CategoryAudio')
    for cat in Category.objects.all():
        if cat.audio_file:
            CategoryAudio.objects.create(
                category=cat,
                audio_file=cat.audio_file,
                max_audio_plays=cat.max_audio_plays or 1,
                audio_instruction=cat.audio_instruction or '',
            )


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0029_alter_quizquestion_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='rules',
            field=models.TextField(blank=True, null=True, verbose_name="Kategoriya sharti (userlarga ko'rinadi)"),
        ),
        migrations.CreateModel(
            name='CategoryAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='category_audio/', verbose_name='Audio fayl')),
                ('max_audio_plays', models.IntegerField(default=1, verbose_name='Necha marta eshitish mumkin (0=cheksiz)')),
                ('audio_instruction', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ko'rsatma")),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='groups.category')),
            ],
            options={
                'verbose_name': 'Kategoriya audio',
                'verbose_name_plural': 'Kategoriya audiolari',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.RunPython(migrate_category_audio_forward, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='category',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='category',
            name='audio_instruction',
        ),
        migrations.RemoveField(
            model_name='category',
            name='max_audio_plays',
        ),
        migrations.AlterUniqueTogether(
            name='studentaudioplay',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentaudioplay',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_plays', to='groups.categoryaudio'),
        ),
        migrations.AlterUniqueTogether(
            name='studentaudioplay',
            unique_together={('student', 'group', 'audio', 'exam_session')},
        ),
    ]
