# Generated by Django 5.2.15 on 2026-06-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0030_remove_category_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rules',
            options={'verbose_name': 'Sozlama', 'verbose_name_plural': 'Sozlamalar'},
        ),
        migrations.AddField(
            model_name='rules',
            name='alarm_audio',
            field=models.FileField(blank=True, null=True, upload_to='alarm_audio/', verbose_name='Signalizatsiya musiqasi'),
        ),
        migrations.AddField(
            model_name='rules',
            name='certificate_bg',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_bg/', verbose_name='Sertifikat fon rasmi'),
        ),
        migrations.AddField(
            model_name='rules',
            name='certificate_threshold',
            field=models.IntegerField(default=50, verbose_name='Sertifikat olish uchun minimal ball (%)'),
        ),
    ]
