# Generated by Django 5.2.15 on 2026-06-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0031_alter_rules_options_rules_alarm_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='battery_level',
            field=models.IntegerField(blank=True, null=True, verbose_name='Batareya (%)'),
        ),
    ]
