# Generated by Django 5.2.15 on 2026-06-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0032_add_battery_level_to_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='condition',
            field=models.TextField(blank=True, null=True, verbose_name="Savol sharti (userlarga ko'rinadi)"),
        ),
    ]
